const phoneList = [
    {
      id: 1,
      title: "Google Pixel 7 Pro",
      brand: "Google",
      price: 1200,
      img: "https://www.finder.com.au/niche-builder/6346435b2bcef.png?fit=1200",
      amount: 1,
    },
    {
      id: 2,
      title: "Apple iPhone 14 Pro",
      brand: "Apple",
      price: 1980,
      img: "https://www.finder.com.au/niche-builder/632d12eb3e531.jpg?fit=1200",
      amount: 1,
    },
    {
      id: 3,
      title: "Samsung Galaxy S22 Ultra",
      brand: "Samsung",
      price: 1430,
      img: "https://www.finder.com.au/niche-builder/620ef31f11b33.png?fit=1200",
      amount: 1,
    },
    {
      id: 4,
      title: "Motorola Moto Edge 30 Pro",
      brand: "Motorola",
      price: 980,
      img: "https://www.tradeinn.com/f/13911/139117621/motorola-edge-30-pro-12gb-256gb-6.7-dual-sim-smartphone.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Apple iPhone SE 2022",
      brand: "Apple",
      price: 980,
      img: "https://www.apple.com/newsroom/images/product/iphone/standard/Apple-iPhoneSE-color-lineup-4up-220308_big.jpg.large.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "OPPO Find X5",
      brand: "OPPO",
      price: 1250,
      img: "https://m.media-amazon.com/images/I/71QmFJCJ-ML._AC_SL1500_.jpg",
      amount: 1,
    },
    {
        id: 7,
        title: "Google Pixel 7 Pro",
        brand: "Google",
        price: 1200,
        img: "https://www.finder.com.au/niche-builder/6346435b2bcef.png?fit=1200",
        amount: 1,
      },
      {
        id: 8,
        title: "Apple iPhone 14 Pro",
        brand: "Apple",
        price: 1980,
        img: "https://www.finder.com.au/niche-builder/632d12eb3e531.jpg?fit=1200",
        amount: 1,
      },
      {
        id: 9,
        title: "Samsung Galaxy S22 Ultra",
        brand: "Samsung",
        price: 1430,
        img: "https://www.finder.com.au/niche-builder/620ef31f11b33.png?fit=1200",
        amount: 1,
      },
      {
        id: 10,
        title: "Motorola Moto Edge 30 Pro",
        brand: "Motorola",
        price: 980,
        img: "https://www.tradeinn.com/f/13911/139117621/motorola-edge-30-pro-12gb-256gb-6.7-dual-sim-smartphone.jpg",
        amount: 1,
      },
      {
        id: 11,
        title: "Apple iPhone SE 2022",
        brand: "Apple",
        price: 980,
        img: "https://www.apple.com/newsroom/images/product/iphone/standard/Apple-iPhoneSE-color-lineup-4up-220308_big.jpg.large.jpg",
        amount: 1,
      },
      {
        id: 12,
        title: "OPPO Find X5",
        brand: "OPPO",
        price: 1250,
        img: "https://m.media-amazon.com/images/I/71QmFJCJ-ML._AC_SL1500_.jpg",
        amount: 1,
      },
  ];
  export default phoneList;